# Android Build Workflow using GitHub Actions
name: Android Build

on:
  push:
    branches: [main]  # Runs on push to main branch
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Expo prebuild (Android)
        run: npx expo prebuild --platform android

      - name: Build Android (simulate)
        run: echo "Android build complete ✅ (simulated)"
